(function () {
  "use strict";

  // Make sure the Supabase library is available
  if (!window.supabase || typeof window.supabase.createClient !== "function") {
    console.error("Supabase library is not loaded.");
    return;
  }

  // These are generated by Netlify during the build
  const supabaseUrl = window.SUPABASE_URL;
  const supabaseAnonKey = window.SUPABASE_ANON_KEY;

  if (!supabaseUrl) {
    console.error("SUPABASE_URL is missing.");
    return;
  }

  if (!supabaseAnonKey) {
    console.error("SUPABASE_ANON_KEY is missing.");
    return;
  }

  // Create the Supabase client
  const supabaseClient = window.supabase.createClient(
    supabaseUrl,
    supabaseAnonKey
  );

  // Make it available to the rest of the website
  window.supabaseClient = supabaseClient;

  console.log("Supabase client initialized successfully.");

  // --------------------------------------------------
  // SIGN-IN PAGE
  // --------------------------------------------------

  const loginForm = document.getElementById("login-form");

  if (loginForm) {
    loginForm.addEventListener("submit", async function (event) {
      event.preventDefault();

      const emailInput = document.getElementById("email");
      const passwordInput = document.getElementById("password");
      const message = document.getElementById("login-message");
      const button = loginForm.querySelector("button[type='submit']");

      const email = emailInput ? emailInput.value.trim() : "";
      const password = passwordInput ? passwordInput.value : "";

      if (!email || !password) {
        if (message) {
          message.textContent = "Please enter your email and password.";
          message.className = "form-message error";
        }
        return;
      }

      if (button) {
        button.disabled = true;
        button.textContent = "Signing in...";
      }

      if (message) {
        message.textContent = "";
        message.className = "form-message";
      }

      try {
        const { data, error } =
          await supabaseClient.auth.signInWithPassword({
            email: email,
            password: password
          });

        if (error) {
          console.error("Supabase login error:", error);

          if (message) {
            message.textContent = error.message;
            message.className = "form-message error";
          }

          if (button) {
            button.disabled = false;
            button.textContent = "Sign in";
          }

          return;
        }

        if (!data || !data.session) {
          throw new Error("Login succeeded but no session was created.");
        }

        console.log("Administrator login successful.");

        if (message) {
          message.textContent = "Login successful. Opening admin dashboard...";
          message.className = "form-message success";
        }

        window.location.href = "admin.html";

      } catch (error) {
        console.error("Login exception:", error);

        if (message) {
          message.textContent =
            error.message || "Unable to sign in. Please try again.";
          message.className = "form-message error";
        }

        if (button) {
          button.disabled = false;
          button.textContent = "Sign in";
        }
      }
    });
  }

  // --------------------------------------------------
  // PROTECT ADMIN PAGE
  // --------------------------------------------------

  if (window.location.pathname.endsWith("/admin.html")) {
    supabaseClient.auth.getSession().then(function ({ data }) {
      if (!data || !data.session) {
        window.location.href = "sign-in.html";
      }
    });
  }

  // --------------------------------------------------
  // LOGOUT
  // --------------------------------------------------

  const logoutButton = document.getElementById("logout-btn");

  if (logoutButton) {
    logoutButton.addEventListener("click", async function () {
      await supabaseClient.auth.signOut();
      window.location.href = "sign-in.html";
    });
  }

  // Make client available globally
  window.PrintInnovationSupabase = supabaseClient;

})();
